export const GET_CALENDAR = Symbol('GET_CALENDAR');
export const GET_CALENDAR_SUCCESS = Symbol('GET_CALENDAR_SUCCESS');
export const GET_CALENDAR_FAILURE = Symbol('GET_CALENDAR_FAILURE');

export const UPDATE_CALENDAR = Symbol('UPDATE_CALENDAR');
export const UPDATE_CALENDAR_SUCCESS = Symbol('UPDATE_CALENDAR_SUCCESS');
export const UPDATE_CALENDAR_FAILURE = Symbol('UPDATE_CALENDAR_FAILURE');
