export const SUBMIT_CONTRACT = Symbol('SUBMIT_CONTRACT');
export const SUBMIT_CONTRACT_SUCCESS = Symbol('SUBMIT_CONTRACT_SUCCESS');
export const SUBMIT_CONTRACT_FAIL = Symbol('SUBMIT_CONTRACT_FAIL');

export const GET_PARTNERS = Symbol('GET_PARTNERS');
export const GET_PARTNERS_SUCCESS = Symbol('GET_PARTNERS_SUCCESS');
export const GET_PARTNERS_FAIL = Symbol('GET_PARTNERS_FAIL');

export const SUBMIT_DOCUMENT = Symbol('SUBMIT_DOCUMENT');
export const SUBMIT_DOCUMENT_SUCCESS = Symbol('SUBMIT_DOCUMENT_SUCCESS');
export const SUBMIT_DOCUMENT_FAIL = Symbol('SUBMIT_DOCUMENT_FAIL');
