export const GET_RECRUITMENTS = Symbol('GET_RECRUITMENTS');
export const GET_RECRUITMENTS_SUCCESS = Symbol('GET_RECRUITMENTS_SUCCESS');
export const GET_RECRUITMENTS_ERROR = Symbol('GET_RECRUITMENTS_ERROR');

export const SAVE_NEW_RECRUITMENT = Symbol('SAVE_NEW_RECRUITMENT');
export const SAVE_NEW_RECRUITMENT_SUCCESS = Symbol(
  'SAVE_NEW_RECRUITMENT_SUCCESS',
);
export const SAVE_NEW_RECRUITMENT_ERROR = Symbol('SAVE_NEW_RECRUITMENT_ERROR');

export const UPDATE_RECRUITMENT = Symbol('UPDATE_RECRUITMENT');
export const UPDATE_RECRUITMENT_SUCCESS = Symbol('UPDATE_RECRUITMENT_SUCCESS');
export const UPDATE_RECRUITMENT_ERROR = Symbol('UPDATE_RECRUITMENT_ERROR');
