export const GET_PARTNERS = Symbol('GET_PARTNERS');
export const GET_PARTNERS_SUCCESS = Symbol('GET_PARTNERS_SUCCESS');
export const GET_PARTNERS_ERROR = Symbol('GET_PARTNERS_ERROR');

export const SAVE_NEW_PARTNER = Symbol('SAVE_NEW_PARTNER');
export const SAVE_NEW_PARTNER_SUCCESS = Symbol('SAVE_NEW_PARTNER_SUCCESS');
export const SAVE_NEW_PARTNER_ERROR = Symbol('SAVE_NEW_PARTNER_ERROR');

export const UPDATE_PARTNER = Symbol('UPDATE_PARTNER');
export const UPDATE_PARTNER_SUCCESS = Symbol('UPDATE_PARTNER_SUCCESS');
export const UPDATE_PARTNER_ERROR = Symbol('UPDATE_PARTNER_ERROR');
