export const GET_CONTRACTS = Symbol('GET_CONTRACTS');
export const GET_CONTRACTS_SUCCESS = Symbol('GET_CONTRACTS_SUCCESS');
export const GET_CONTRACTS_FAIL = Symbol('GET_CONTRACTS_FAIL');

export const SUBMIT_SIGNATURE = Symbol('SUBMIT_SIGNATURE');
export const SUBMIT_SIGNATURE_SUCCESS = Symbol('SUBMIT_SIGNATURE_SUCCESS');
export const SUBMIT_SIGNATURE_FAIL = Symbol('SUBMIT_SIGNATURE_FAIL');

export const GET_DOCUMENTS = Symbol('GET_DOCUMENTS');
export const GET_DOCUMENTS_SUCCESS = Symbol('GET_DOCUMENTS_SUCCESS');
export const GET_DOCUMENTS_FAIL = Symbol('GET_DOCUMENTS_FAIL');

export const GET_PARTNERS = Symbol('GET_PARTNERS');
export const GET_PARTNERS_SUCCESS = Symbol('GET_PARTNERS_SUCCESS');
export const GET_PARTNERS_FAIL = Symbol('GET_PARTNERS_FAIL');

export const SUBMIT_DOCUMENT = Symbol('SUBMIT_DOCUMENT');
export const SUBMIT_DOCUMENT_SUCCESS = Symbol('SUBMIT_DOCUMENT_SUCCESS');
export const SUBMIT_DOCUMENT_FAIL = Symbol('SUBMIT_DOCUMENT_FAIL');

export const GET_DOCUMENTS_ROMEXPO = Symbol('GET_DOCUMENTS_ROMEXPO');
export const GET_DOCUMENTS_ROMEXPO_SUCCESS = Symbol(
  'GET_DOCUMENTS_ROMEXPO_SUCCESS',
);
export const GET_DOCUMENTS_ROMEXPO_FAIL = Symbol('GET_DOCUMENTS_ROMEXPO_FAIL');

export const GET_DOCUMENTS_CLUJ = Symbol('GET_DOCUMENTS_CLUJ');
export const GET_DOCUMENTS_CLUJ_SUCCESS = Symbol('GET_DOCUMENTS_CLUJ_SUCCESS');
export const GET_DOCUMENTS_CLUJ_FAIL = Symbol('GET_DOCUMENTS_CLUJ_FAIL');

export const GET_DOCUMENTS_TITAN = Symbol('GET_DOCUMENTS_TITAN');
export const GET_DOCUMENTS_TITAN_SUCCESS = Symbol(
  'GET_DOCUMENTS_TITAN_SUCCESS',
);
export const GET_DOCUMENTS_TITAN_FAIL = Symbol('GET_DOCUMENTS_TITAN_FAIL');

export const GET_COMPANY_LOCATIONS = Symbol('GET_COMPANY_LOCATIONS');
export const GET_COMPANY_LOCATIONS_SUCCESS = Symbol(
  'GET_COMPANY_LOCATIONS_SUCCESS',
);
export const GET_COMPANY_LOCATIONS_FAIL = Symbol('GET_COMPANY_LOCATIONS_FAIL');
