export const GET_PAYROLL_DATA = Symbol('GET_PAYROLL_DATA');
export const GET_PAYROLL_DATA_SUCCESS = Symbol('GET_PAYROLL_DATA_SUCCESS');
export const GET_PAYROLL_DATA_FAILURE = Symbol('GET_PAYROLL_DATA_FAILURE');
